apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: pv
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/data
    type: Directory
  claimRef:
    name: pvc
    namespace: lnmp