apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    mysql: service
  namespace: lnmp
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - targetPort: mysql-port
      protocol: TCP
      port: 3306
      name: mysql-service-port
      nodePort: 32004