apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: lnmp
  labels:
    nginx: service
spec:
  type: NodePort
  selector:
    lnmp: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: nginx-port
      nodePort: 32003
      name: service-nginx-port